BlockBot.Web/Controllers/DocsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlockBot.Web.Controllers
{
    [AllowAnonymous]
    public class DocsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateTwilioAccount()
        {
            return View();
        }

        public IActionResult Components()
        {
            return View();
        }

        public IActionResult EndConversation()
        {
            return View();
        }

        public IActionResult Prompts()
        {
            return View();
        }

        public IActionResult StartConversation()
        {
            return View();
        }
    }
}

BlockBot.Web/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Amazon.S3;
using BlockBot.Common.Data;
using BlockBot.Module.Aws.Models;
using BlockBot.Module.Aws.ServiceInterfaces;
using BlockBot.Module.Aws.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlockBot.Web.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ApplicationUserManager _userManager;
        private readonly IApiGatewayService _apiGatewayService;
        private readonly ILambdaService _lambdaService;
        private readonly IS3Service _s3Service;
        private DynamoDbService _dynamoDbService;

        public ProjectsController(ApplicationDbContext context,
            ApplicationUserManager userManager,
            IApiGatewayService apiGatewayService,
            ILambdaService lambdaService,
            IS3Service s3Service,
            DynamoDbService dynamoDbService){
            _context = context;
            _userManager = userManager;
            _apiGatewayService = apiGatewayService;
            _lambdaService = lambdaService;
            _s3Service = s3Service;
            _dynamoDbService = dynamoDbService;
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (project.OwnerId != user.Id)
            {
                return Unauthorized();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IsPublic,Description,TwilioServiceSID,TwilioAccountSID,TwilioAuthToken")] Project project)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
                }
                project.OwnerId = user.Id;
                project.XML =
                    "<xml xmlns=\"http://www.w3.org/1999/xhtml\" id=\"workspaceBlocks\" style=\"display: none;\"></xml>";
                project.Id = Guid.NewGuid();

                // TODO create IAM user for project?

                // create API Gateway
                // TODO convert this to use prod url after sufficient debugging
                ApiGatewayRestApi result = await _apiGatewayService.CreateApiGateway(
                    project.Id.ToString(),
                    "https://localhost:44305/Projects/Details/" + project.Id);
                project.RestApiId = result.RestApiId;
                _context.Add(project);

                // create s3 bucket
                bool bucketCreateSucceeded = await _s3Service.CreateOrUpdateBucket(project.S3BucketName(), S3CannedACL.Private);
                if (!bucketCreateSucceeded)
                {
                    string message = "Unable to create an S3 bucket.";
                    // TODO log message to ILogger
                    return RedirectToAction("Error", "Home", new { message });
                }

                // TODO create DynamoDB table
                await _dynamoDbService.Create(project.Id);

                // add Twilio integration
                Service twilioService = await _context.Services.FirstOrDefaultAsync(x => x.Name == "Twilio");
                if (twilioService == null)
                {
                    string message = "Unable to locate the Twilio service.";
                    // TODO log message to ILogger
                    return RedirectToAction("Error", "Home", new { message });
                }
                _context.Integrations.Add(new Integration
                {
                    Id = Guid.NewGuid(),
                    ProjectId = project.Id,
                    ServiceId = twilioService.Id
                });

                // save changes
                await _context.SaveChangesAsync();
                
                return RedirectToAction("Dashboard", "Dashboard");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (project.OwnerId != user.Id)
            {
                return Unauthorized();
            }

            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description,IsPublic,TwilioServiceSID,TwilioAccountSID,TwilioAuthToken")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            Project originalProject = await _context.Projects.FindAsync(id);
            if (originalProject == null)
            {
                return NotFound();
            }
            if (originalProject.OwnerId != user.Id)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    originalProject.Name = project.Name;
                    originalProject.Description = project.Description;
                    originalProject.IsPublic = project.IsPublic;
                    originalProject.TwilioAccountSID = project.TwilioAccountSID;
                    originalProject.TwilioServiceSID = project.TwilioServiceSID;
                    originalProject.TwilioAuthToken = project.TwilioAuthToken;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Dashboard", "Dashboard");
            }

            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (project.OwnerId != user.Id)
            {
                return Unauthorized();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var project = await _context.Projects.FindAsync(id);

            if (project == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (project.OwnerId != user.Id)
            {
                return Unauthorized();
            }

            try
            {
                // delete API gateway
                ApiGatewayRestApiDelete y = await _apiGatewayService.DeleteApiGateway(project.RestApiId);
                // TODO throw error on failure

            }
            catch (Exception)
            {
                // do nothing
            }
            

            // delete lambdas

BlockBot.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlockBot.Common.Data;
using BlockBot.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SQLitePCL;

namespace BlockBot.Web.Controllers
{
    public class UserController : Controller
    {
        private ApplicationDbContext _context;
        private ApplicationUserManager _userManager;

        public UserController(ApplicationDbContext context, ApplicationUserManager userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Projects(Guid id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());

            if (user == null)
            {
                return NotFound();
            }

            var model = new User_Projects_Model
            {
                User = user,
                Projects = _context.Projects.Where(x => x.OwnerId == user.Id && x.IsPublic).ToList()
            };

            return View(model);
        }
    }
}

BlockBot.Web/Controllers/WorkspaceController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Amazon;
using BlockBot.Common.Data;
using BlockBot.module.Integrations.Services;
using BlockBot.Module.Aws.ServiceInterfaces;
using BlockBot.Module.Google.Services;
using BlockBot.Module.Twilio.ServiceInterfaces;
using BlockBot.Web.Models;
using Google.Apis.Calendar.v3.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace BlockBot.Web.Controllers
{
    public class WorkspaceController : Controller
    {
        private readonly GoogleCalendarService _googleCalendarService;
        private readonly IntegrationCreationService _integrationCreationService;
        private readonly ILogger<WorkspaceController> _logger;
        private readonly ApplicationUserManager _userManager;
        private ApplicationDbContext _context;

        public WorkspaceController(ApplicationDbContext context,
            ApplicationUserManager userManager,
            IApiGatewayService apiGatewayService,
            ILambdaService lambdaService,
            IS3Service s3Service,
            ITwilioService twilioService,
            IntegrationCreationService integrationCreationService,
            ILogger<WorkspaceController> logger,
            GoogleCalendarService googleCalendarService)
        {
            _context = context;
            _userManager = userManager;
            _integrationCreationService = integrationCreationService;
            _logger = logger;
            _googleCalendarService = googleCalendarService;
        }

        /// <summary>
        /// </summary>
        /// <param name="id">The project id</param>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<IActionResult> Workspace(Guid id)
        {
            ViewData["Message"] = "A workspace for editing programs";

            Project project = await _context.Projects
                .FirstOrDefaultAsync(m => m.Id == id);

            if (project == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);

            var model = new WorkspaceModel
            {
                Project = project,
                IsOwner = true,//user != null && project.OwnerId == user.Id,
                IsLoggedIn = user != null
            };

            ApplicationUserClaim claim = user?.Claims.FirstOrDefault(x => x.ClaimType == "GoogleRefreshToken");
            if (claim != null)
            {
                var l = _googleCalendarService
                    .ListCalendars(ref _context, user.NormalizedUserName);
                
                bool needsAuth = l.Match(x => false, y => true);
                if (needsAuth)
                {
                    return this.RedirectToAction("ReauthorizationRequest", "Account", new {provider="Google"});
                }

                var calendarList = l.LeftOrDefault();
                if (calendarList != null)
                {
                    model.CalendarList = l.LeftOrDefault().Items
                        .Where(x => x.AccessRole == "writer" || x.AccessRole == "owner")
                        .ToList();
                }
            }

            return View(model);
        }

        [HttpPut]
        public async Task<IActionResult> PutProjectXml(Guid id, string xml)
        {
            Project project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound($"Unable to load project with ID '{id}'.");
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (project.OwnerId != user.Id)
            {
                //return Unauthorized();
            }

            project.XML = xml;
            await _context.SaveChangesAsync();

            return NoContent();
        }

        [HttpPut]
        public async Task<IActionResult> PutProjectCode(Guid id, string code)
        {
            Project project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound($"Unable to load project with ID '{id}'.");
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (project.OwnerId != user.Id)
            {
                //return Unauthorized();
            }

            try
            {
                // TODO use project-specific role? use user-specific role?
                string role = "arn:aws:iam::687311858360:role/service-role/fundamentals_chatbot";
                await Task.WhenAll(
                    _context
                        .Integrations
                        .Where(x => x.ProjectId == id)
                        .Select(integration =>
                            _integrationCreationService
                                .Integrate(
                                    integration.Service.Name,
                                    id,
                                    RegionEndpoint.USEast1,
                                    role,
                                    project.RestApiId,
                                    project.S3BucketName(),
                                    code)));
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"There was an error creating/updating integrations for project id '{id}'.");
                return NoContent();
            }

            return NoContent();
        }
    }
}

BlockBot.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h2>About BlockBot</h2>
<p>BlockBot is a platform for building interactive chatbots without programming.</p>
<p>
    Using BlockBot and our custom blocks, businesses can create personalized appointment-scheduling chatbots.
    With BlockBot, individuals with no programming experience can create chatbots.
</p>
<p>
    BlockBot allows creation of chat bots that interface with business' public calendar to show available appointment times.
    Using BlockBot, chat bots can send text and/or email reminders. This is accomplished using services like Twilio.
</p>
<h4>Our Team</h4>
<ul>
    <li>Harley Waldstein</li>
    <li>Rae Corrigan</li>
    <li>Callum Duff</li>
    <li>Kevin Chin</li>
    <li>Gaurav Singh Jawla</li>
    <li>Samuel Aboye</li>
    <li>Siddarth Kannan</li>
</ul>
<br/>
<img src="~/images/logo_built_on_blockly.png" style="height: 3em; width: auto;"/>

BlockBot.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<center>
    <h2>@ViewData["Title"]</h2>
    <h5>@ViewData["Message"]</h5>
    <p>We'd love to hear from you!</p>
    <p>
        Want to know more about us? Visit our <strong>about us</strong> <a asp-controller="Home" asp-action="About">page</a> .
    </p>
</center>
<br>
<h5><strong>VISIT US</strong></h5>
<address>
    15 Schaffer Hall<br />
    Iowa City, IA 52242<br />
    <strong>Ph No: </strong>
    <a href="tel:+13192680100">319.268.0100</a>
</address>
<br>
<h5><strong>EMAIL US</strong></h5>
<address><strong>Support:</strong> <a href="mailto:admin@blockbot.io">admin@blockbot.io</a><br /></address>

BlockBot.Web/Views/Home/Index.cshtml
@using BlockBot.Common.Data
@model IList<BlockBot.Common.Data.Project>
@{
    ViewData["Title"] = "Home Page";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">BlockBot: Create Chat Bots for Fun and Profit</h1>
        <p class="lead text-muted">Use drag-and-drop blocks to build chat bots, connect with your clients, and create an innovative user experience.</p>
        <p>
            <a asp-controller="Account" asp-action="Register" class="btn btn-primary my-2">Create an Account</a>
            <a asp-controller="Docs" asp-action="Index" class="btn btn-secondary my-2">Learn More</a>
        </p>
    </div>
</section>

@if (Model.Count > 0)
{
    <!-- From http://getbootstrap.com/docs/4.1/examples/album/ -->
<div>
    <h2 class="">Popular Projects</h2>
    <br />
    <div class="container">
        <div class="row">
            @foreach (Project project in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="display: block; height: 225px; width: 100%;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1666463bcbf%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1666463bcbf%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.54999923706055%22%20y%3D%22120.18000011444092%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                        <div class="card-body">
                            <h4 class="card-title">@project.Name</h4>
                            @if (project.Description.Length > 0)
                            {
                                <p class="card-text">@project.Description</p>
                            }
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" asp-controller="Workspace" asp-action="Workspace" asp-route-id="@project.Id">View</a>
                                    <a class="btn btn-sm btn-outline-secondary" asp-controller="Projects" asp-action="Clone" asp-route-id="@project.Id">Clone</a>
                                </div>
                                <small class="text-muted"><a asp-controller="User" asp-action="Projects" asp-route-id="@project.OwnerId">@project.Owner.UserName</a></small> <!-- TODO make like to page of user's public projects, user's "profile" -->
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
}