BlockBot.Web/Controllers/AccountManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using BlockBot.Common.Data;
using BlockBot.Module.Google.Models;
using BlockBot.Web.Models.AccountManage;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace BlockBot.Web.Controllers
{
    public class AccountManageController : Controller
    {
        private readonly IEmailSender _emailSender;
        private readonly ILogger<AccountManageController> _logger;
        private readonly ApplicationSignInManager _signInManager;
        private readonly UrlEncoder _urlEncoder;
        private readonly ApplicationUserManager _userManager;

        public AccountManageController(
            ApplicationUserManager userManager,
            ApplicationSignInManager signInManager,
            UrlEncoder urlEncoder,
            ILogger<AccountManageController> logger,
            IEmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _urlEncoder = urlEncoder;
            _logger = logger;
            _emailSender = emailSender;
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            bool hasPassword = await _userManager.HasPasswordAsync(user);
            if (!hasPassword)
            {
                return RedirectToAction("SetPassword");
            }

            return View("ChangePassword", new ChangePasswordModel());
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("ChangePassword", model);
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            IdentityResult changePasswordResult =
                await _userManager.ChangePasswordAsync(user, model.Input.OldPassword, model.Input.NewPassword);
            if (!changePasswordResult.Succeeded)
            {
                foreach (IdentityError error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View("ChangePassword", model);
            }

            await _signInManager.RefreshSignInAsync(user);
            _logger.LogInformation("User changed their password successfully.");
            TempData["StatusMessage"] = "Your password has been changed.";

            // TODO verify this redirects to the GET version of this page
            return RedirectToAction();
        }

        [HttpGet]
        public async Task<IActionResult> DeletePersonalData()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            DeletePersonalDataModel model = new DeletePersonalDataModel
                {RequirePassword = await _userManager.HasPasswordAsync(user)};

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePersonalData(DeletePersonalDataModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            bool requirePassword = await _userManager.HasPasswordAsync(user);
            if (requirePassword)
            {
                if (!await _userManager.CheckPasswordAsync(user, model.Input.Password))
                {
                    ModelState.AddModelError(string.Empty, "Password not correct.");
                    return View("DeletePersonalData", model);
                }
            }

            IdentityResult result = await _userManager.DeleteAsync(user);
            string userId = await _userManager.GetUserIdAsync(user);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Unexpected error occurred deleting user with ID '{userId}'.");
            }

            await _signInManager.SignOutAsync();

            _logger.LogInformation("User with ID '{UserId}' deleted themselves.", userId);

            return Redirect("~/");
        }

        [HttpGet]
        public async Task<IActionResult> Disable2fa()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!await _userManager.GetTwoFactorEnabledAsync(user))
            {
                throw new InvalidOperationException(
                    $"Cannot disable 2FA for user with ID '{_userManager.GetUserId(User)}' as it's not currently enabled.");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Disable2fa(string unusedString = null)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            IdentityResult disable2faResult = await _userManager.SetTwoFactorEnabledAsync(user, false);
            if (!disable2faResult.Succeeded)
            {
                throw new InvalidOperationException(
                    $"Unexpected error occurred disabling 2FA for user with ID '{_userManager.GetUserId(User)}'.");
            }

            _logger.LogInformation("User with ID '{UserId}' has disabled 2fa.", _userManager.GetUserId(User));
            TempData["StatusMessage"] =
                "2fa has been disabled. You can reenable 2fa when you setup an authenticator app.";
            return RedirectToAction("TwoFactorAuthentication");
        }

        [HttpPost]
        public async Task<IActionResult> DownloadPersonalData()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            _logger.LogInformation("User with ID '{UserId}' asked for their personal data.",
                _userManager.GetUserId(User));

            // Only include personal data for download
            Dictionary<string, string> personalData = new Dictionary<string, string>();
            IEnumerable<PropertyInfo> personalDataProps = typeof(IdentityUser).GetProperties().Where(
                prop => Attribute.IsDefined(prop, typeof(PersonalDataAttribute)));
            foreach (PropertyInfo p in personalDataProps)
            {
                personalData.Add(p.Name, p.GetValue(user)?.ToString() ?? "null");
            }

            Response.Headers.Add("Content-Disposition", "attachment; filename=PersonalData.json");
            return new FileContentResult(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(personalData)),
                "text/json");
        }

        [HttpGet]
        public async Task<IActionResult> EnableAuthenticator()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            EnableAuthenticatorModel model = await LoadSharedKeyAndQrCodeUri(user, new EnableAuthenticatorModel());

            return View("EnableAuthenticator", model);
        }

        [HttpPost]
        public async Task<IActionResult> EnableAuthenticator(EnableAuthenticatorModel model)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                model = await LoadSharedKeyAndQrCodeUri(user, model);
                return View("EnableAuthenticator", model);
            }

            // Strip spaces and hypens
            string verificationCode = model.Input.Code.Replace(" ", string.Empty).Replace("-", string.Empty);

            bool is2faTokenValid = await _userManager.VerifyTwoFactorTokenAsync(
                user, _userManager.Options.Tokens.AuthenticatorTokenProvider, verificationCode);

            if (!is2faTokenValid)
            {
                ModelState.AddModelError("Input.Code", "Verification code is invalid.");
                model = await LoadSharedKeyAndQrCodeUri(user, model);
                return View("EnableAuthenticator", model);
            }

            await _userManager.SetTwoFactorEnabledAsync(user, true);
            string userId = await _userManager.GetUserIdAsync(user);
            _logger.LogInformation("User with ID '{UserId}' has enabled 2FA with an authenticator app.", userId);

            TempData["StatusMessage"] = "Your authenticator app has been verified.";

BlockBot.Web/Controllers/DocsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlockBot.Web.Controllers
{
    [AllowAnonymous]
    public class DocsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateTwilioAccount()
        {
            return View();
        }

        public IActionResult Components()
        {
            return View();
        }

        public IActionResult EndConversation()
        {
            return View();
        }

        public IActionResult Prompts()
        {
            return View();
        }

        public IActionResult StartConversation()
        {
            return View();
        }
    }
}

BlockBot.Web/Views/Shared/_AccountManageLayout.cshtml
@{ 
    Layout = "_Layout";
}

<h2>Manage your account</h2>

<div>
    <h4>Change your account settings</h4>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <partial name="_AccountManageNav" />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}

BlockBot.Web/Views/Shared/_AccountManageNav.cshtml
@using BlockBot.Common.Data
@using BlockBot.Web.Views.Shared
@inject ApplicationSignInManager SignInManager
@{
    var hasExternalLogins = (await SignInManager.GetExternalAuthenticationSchemesAsync()).Any();
}

<ul class="nav nav-pills flex-column">

    <li class="nav-item"><a asp-controller="AccountManage" asp-action="Index" class="@AccountManageNavPages.IndexNavClass(ViewContext)">Profile</a></li>
    <li class="nav-item"><a id="change-password" asp-controller="AccountManage" asp-action="ChangePassword" class="@AccountManageNavPages.ChangePasswordNavClass(ViewContext)">Password</a></li>
    @if (hasExternalLogins)
    {
        <li class="nav-item"><a id="external-login" asp-controller="AccountManage" asp-action="ExternalLogins" class="@AccountManageNavPages.ExternalLoginsNavClass(ViewContext)">External logins</a></li>
    }
    <li class="nav-item"><a asp-controller="AccountManage" asp-action="TwoFactorAuthentication" class="@AccountManageNavPages.TwoFactorAuthenticationNavClass(ViewContext)">Two-factor authentication</a></li>
    <li class="nav-item"><a asp-controller="AccountManage" asp-action="PersonalData" class="@AccountManageNavPages.PersonalDataNavClass(ViewContext)">Personal data</a></li>
</ul>

BlockBot.Web/Views/Shared/_AccountManageStatusMessage.cshtml
@model string

@if (!string.IsNullOrEmpty(Model))
{
    string statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

BlockBot.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - FundamentalsChatbot</title>

    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Css", false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">BlockBot</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <!-- TODO set active programmatically -->
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a> <!-- TODO set current programmatically -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Docs" asp-action="Index">Docs</a>
                    </li>

                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>

    </nav>
</header>

<main role="main" class="container body-content">
    <partial name="_CookieConsentPartial"/>
    
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-primary alert-dismissible" role="alert">
            @TempData["Message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    @RenderBody()
    <hr/>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Back to top</a>
            </p>
            <p>&copy; @DateTime.Now.Year - BotBuilder <a asp-controller="Home" asp-action="Privacy">Privacy Policy</a></p>
        </div>
    </footer>
</main>

<environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/popper.js/popper.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/popper.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", false)
</body>
</html>

BlockBot.Web/Views/Shared/_ToolboxPartial.cshtml
@model IList<Google.Apis.Calendar.v3.Data.CalendarListEntry>
<xml xmlns="http://www.w3.org/1999/xhtml" id="toolbox" style="display: none;">
    <category name="Logic" colour="#5C81A6">
        <block type="controls_if"></block>
        <block type="logic_compare">
            <field name="OP">EQ</field>
        </block>
        <block type="logic_operation">
            <field name="OP">AND</field>
        </block>
        <block type="logic_negate"></block>
        <block type="logic_boolean">
        </block>
        <field name="BOOL">TRUE</field>
        <block type="logic_null"></block>
        <block type="logic_ternary"></block>
    </category>
<category name="Loops" colour="#5CA65C">
    <block type="controls_repeat_ext">
        <value name="TIMES">
            <shadow type="math_number">
                <field name="NUM">10</field>
            </shadow>
        </value>
    </block>
    <block type="controls_whileUntil">
        <field name="MODE">WHILE</field>
    </block>
    <block type="controls_for">
        <field name="VAR" id="a/+%Q`VQ$R#I^}EW8jd_" variabletype="">i</field>
        <value name="FROM">
            <shadow type="math_number">
                <field name="NUM">1</field>
            </shadow>
        </value>
        <value name="TO">
            <shadow type="math_number">
                <field name="NUM">10</field>
            </shadow>
        </value>
        <value name="BY">
            <shadow type="math_number">
                <field name="NUM">1</field>
            </shadow>
        </value>
    </block>
    <block type="controls_forEach">
        <field name="VAR" id="CHurzBc#kSJ#Tr.Y8DI0" variabletype="">j</field>
    </block>
    <block type="controls_flow_statements">
        <field name="FLOW">BREAK</field>
    </block>
</category>
<category name="Math" colour="#5C68A6">
    <block type="math_number">
        <field name="NUM">0</field>
    </block>
    <block type="math_arithmetic">
        <field name="OP">ADD</field>
        <value name="A">
            <shadow type="math_number">
                <field name="NUM">1</field>
            </shadow>
        </value>
        <value name="B">
            <shadow type="math_number">
                <field name="NUM">1</field>
            </shadow>
        </value>
    </block>
    <block type="math_single">
        <field name="OP">ROOT</field>
        <value name="NUM">
            <shadow type="math_number">
                <field name="NUM">9</field>
            </shadow>
        </value>
    </block>
    <block type="math_trig">
        <field name="OP">SIN</field>
        <value name="NUM">
            <shadow type="math_number">
                <field name="NUM">45</field>
            </shadow>
        </value>
    </block>
    <block type="math_constant">
        <field name="CONSTANT">PI</field>
    </block>
    <block type="math_number_property">
        <mutation divisor_input="false"></mutation>
        <field name="PROPERTY">EVEN</field>
        <value name="NUMBER_TO_CHECK">
            <shadow type="math_number">
                <field name="NUM">0</field>
            </shadow>
        </value>
    </block>
    <block type="math_round">
        <field name="OP">ROUND</field>
        <value name="NUM">
            <shadow type="math_number">
                <field name="NUM">3.1</field>
            </shadow>
        </value>
    </block>
    <block type="math_on_list">
        <mutation op="SUM"></mutation>
        <field name="OP">SUM</field>
    </block>
    <block type="math_modulo">
        <value name="DIVIDEND">
            <shadow type="math_number">
                <field name="NUM">64</field>
            </shadow>
        </value>
        <value name="DIVISOR">
            <shadow type="math_number">
                <field name="NUM">10</field>
            </shadow>
        </value>
    </block>
    <block type="math_constrain">
        <value name="VALUE">
            <shadow type="math_number">
                <field name="NUM">50</field>
            </shadow>
        </value>
        <value name="LOW">
            <shadow type="math_number">
                <field name="NUM">1</field>
            </shadow>
        </value>
        <value name="HIGH">
            <shadow type="math_number">
                <field name="NUM">100</field>
            </shadow>
        </value>
    </block>
    <block type="math_random_int">
        <value name="FROM">
            <shadow type="math_number">
                <field name="NUM">1</field>
            </shadow>
        </value>
        <value name="TO">
            <shadow type="math_number">
                <field name="NUM">100</field>
            </shadow>
        </value>
    </block>
    <block type="math_random_float"></block>
</category>
<category name="Text" colour="#5CA68D">
    <block type="text">
        <field name="TEXT"></field>
    </block>
    <block type="text_join">
        <mutation items="2"></mutation>
    </block>
    <block type="text_append">
        <field name="VAR" id="`J8gpn6tm+UYntC?3Nu2" variabletype="">item</field>
        <value name="TEXT">
            <shadow type="text">
                <field name="TEXT"></field>
            </shadow>
        </value>
    </block>
    <block type="text_length">
        <value name="VALUE">
            <shadow type="text">
                <field name="TEXT">abc</field>
            </shadow>
        </value>
    </block>
    <block type="text_isEmpty">
        <value name="VALUE">
            <shadow type="text">
                <field name="TEXT"></field>
            </shadow>
        </value>
    </block>
    <block type="text_indexOf">
        <field name="END">FIRST</field>
        <value name="VALUE">
            <block type="variables_get">
                <field name="VAR" id="dl/gBK6$/v2P@sNRO9_?" variabletype="">text</field>
            </block>
        </value>
        <value name="FIND">
            <shadow type="text">
                <field name="TEXT">abc</field>
            </shadow>
        </value>
    </block>
    <block type="text_charAt">
        <mutation at="true"></mutation>
        <field name="WHERE">FROM_START</field>
        <value name="VALUE">
            <block type="variables_get">
                <field name="VAR" id="dl/gBK6$/v2P@sNRO9_?" variabletype="">text</field>
            </block>
        </value>
    </block>
    <block type="text_getSubstring">
        <mutation at1="true" at2="true"></mutation>
        <field name="WHERE1">FROM_START</field>
        <field name="WHERE2">FROM_START</field>
        <value name="STRING">
            <block type="variables_get">
                <field name="VAR" id="dl/gBK6$/v2P@sNRO9_?" variabletype="">text</field>
            </block>
        </value>
    </block>
    <block type="text_changeCase">
        <field name="CASE">UPPERCASE</field>
        <value name="TEXT">
            <shadow type="text">
                <field name="TEXT">abc</field>
            </shadow>
        </value>
    </block>
    <block type="text_trim">
        <field name="MODE">BOTH</field>
        <value name="TEXT">
            <shadow type="text">
                <field name="TEXT">abc</field>
            </shadow>
        </value>
    </block>
    <block type="text_print">
        <value name="TEXT">
            <shadow type="text">
                <field name="TEXT">abc</field>
            </shadow>
        </value>
    </block>
    <block type="text_prompt_ext">
        <mutation type="TEXT"></mutation>
        <field name="TYPE">TEXT</field>
        <value name="TEXT">
            <shadow type="text">
                <field name="TEXT">abc</field>
            </shadow>
        </value>
    </block>
</category>
<category name="Lists" colour="#745CA6">
    <block type="lists_create_with">
        <mutation items="0"></mutation>
    </block>
    <block type="lists_create_with">
        <mutation items="3"></mutation>
    </block>
    <block type="lists_repeat">
        <value name="NUM">
            <shadow type="math_number">
                <field name="NUM">5</field>
            </shadow>
        </value>
    </block>
    <block type="lists_length"></block>
    <block type="lists_isEmpty"></block>
    <block type="lists_indexOf">
        <field name="END">FIRST</field>
        <value name="VALUE">
            <block type="variables_get">
                <field name="VAR" id="flGS@@}7NczkVFSXtiMt/" variabletype="">list</field>
            </block>
        </value>
    </block>
    <block type="lists_getIndex">
        <mutation statement="false" at="true"></mutation>
        <field name="MODE">GET</field>
        <field name="WHERE">FROM_START</field>
        <value name="VALUE">
            <block type="variables_get">
                <field name="VAR" id="flGS@@}7NczkVFSXtiMt/" variabletype="">list</field>
            </block>
        </value>
    </block>
    <block type="lists_setIndex">
        <mutation at="true"></mutation>
        <field name="MODE">SET</field>
        <field name="WHERE">FROM_START</field>
        <value name="LIST">
            <block type="variables_get">
                <field name="VAR" id="flGS@@}7NczkVFSXtiMt/" variabletype="">list</field>
            </block>
        </value>
    </block>
    <block type="lists_getSublist">
        <mutation at1="true" at2="true"></mutation>
        <field name="WHERE1">FROM_START</field>
        <field name="WHERE2">FROM_START</field>
        <value name="LIST">
            <block type="variables_get">
                <field name="VAR" id="flGS@@}7NczkVFSXtiMt/" variabletype="">list</field>
            </block>
        </value>
    </block>
    <block type="lists_split">
        <mutation mode="SPLIT"></mutation>
        <field name="MODE">SPLIT</field>
        <value name="DELIM">
            <shadow type="text">
                <field name="TEXT">,</field>
            </shadow>
        </value>
    </block>
    <block type="lists_sort">
        <field name="TYPE">NUMERIC</field>
        <field name="DIRECTION">1</field>
    </block>
</category>
<category name="Colour" colour="#A6745C">
    <block type="colour_picker">
        <field name="COLOUR">#ff0000</field>
    </block>
    <block type="colour_random"></block>
    <block type="colour_rgb">
        <value name="RED">
            <shadow type="math_number">
                <field name="NUM">100</field>
            </shadow>
        </value>
        <value name="GREEN">
            <shadow type="math_number">
                <field name="NUM">50</field>
            </shadow>
        </value>
        <value name="BLUE">
            <shadow type="math_number">
                <field name="NUM">0</field>
            </shadow>
        </value>
    </block>
    <block type="colour_blend">
        <value name="COLOUR1">
            <shadow type="colour_picker">
                <field name="COLOUR">#ff0000</field>
            </shadow>
        </value>
        <value name="COLOUR2">
            <shadow type="colour_picker">
                <field name="COLOUR">#3333ff</field>
            </shadow>
        </value>
        <value name="RATIO">
            <shadow type="math_number">
                <field name="NUM">0.5</field>
            </shadow>
        </value>
    </block>
</category>
<sep></sep>
<category name="Variables" colour="#A65C81" custom="VARIABLE"></category>
<category name="Functions" colour="#9A5CA6" custom="PROCEDURE"></category>
<sep></sep>
@if (Model != null && Model.Count > 0)
{
<category name="Calendars" colour="#5b80a5">
    @foreach (var calendar in Model)
    {

    <block type="calendar_calendar">
        <field name="NAME" editable="false">@calendar.Summary</field>
        <field name="ID">@calendar.Id</field>
    </block>
    }
    <block type="calendar_create_appt"></block>

    <block type="calendar_get_name"></block>
    <block type="calendar_next_available"></block>
</category>
}

<category name="Messages" colour="#5b80a5">
    <block type="start_conversation"></block>
    <block type="end_conversation"></block>
    <block type="get_message_body"></block>
    <block type="get_message_sender"></block>
    <block type="send_message"></block>
</category>
<category name="Options" colour="#5b80a5">
    <block type="options"></block>
    <block type="options_alternative"></block>
    <block type="option"></block>
    <block type="switch"></block>
    <block type="case"></block>
</category>
</xml>